// <auto-generated />
namespace elearning.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update04062018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update04062018));
        
        string IMigrationMetadata.Id
        {
            get { return "201806041557148_Update04062018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
